# Generated by Django 4.1 on 2023-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalitaDiskritis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.IntegerField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')])),
                ('usia', models.IntegerField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('status_gizi', models.IntegerField(choices=[('Gizi Buruk', 'Gizi Buruk'), ('Gizi Kurang', 'Gizi Kurang'), ('Gizi Normal', 'Gizi Normal'), ('Gizi Lebih', 'Gizi Lebih')])),
            ],
        ),
    ]
